config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: 'custom_tokens'
    skip_controllers :authorizations, :applications, :authorized_applications

  end

  resources :conta_bancarias
  resources :seguradoras
  resources :planos

  resources :beneficios

  devise_for :users, path: 'u', controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  devise_for :beneficiarios, path: 'b', controllers: {
    sessions: "beneficiarios/sessions",
    passwords: "beneficiarios/passwords",
    registrations: "beneficiarios/registrations",
    confirmations: "beneficiarios/confirmations",
    unlocks: "beneficiarios/unlocks"
  }


  resources :organizacoes do
    resources :users, controller: 'organizacao_users', path: 'users'
    resources :organizacao_plano, controller: 'organizacao_planos', path: 'planos'
    resources :beneficiarios
  end


  namespace :api, defaults: {format: :json} do
    post 'password_reset' , to: 'passwords#reset'
    post 'confirm_user', to: 'confirmations#confirm'
    namespace :v1 do
      get 'me', to: 'me#me'
      resources :organizacoes do
        get 'beneficiarios/tickets', to: 'tickets#beneficiarios'
        resources :beneficiarios
        resources :organizacao_planos, path: 'planos'
        resources :condicoes
        resources :beneficios
        resources :users, controller: 'organizacao_users', only: [:index,:create]

      end
      resources :seguradoras do
        resources :planos
      end
      resources :users
      resources :organizacao_planos, only: [:create,:update]
      resources :tickets, except: [:update]
      post 'tickets/:id/cancel', to: 'tickets#cancel'
      post 'tickets/:id/execute', to: 'tickets#execute'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/beneficiario.rb
class Beneficiario < BaseUser
  resourcify
  rolify

  validate :titular_nao_pode_ter_titular
  validates :email ,presence: true, email: true
  validates :cpf ,presence: true, cpf: true
  validates :genero ,presence: true
  validates :parentesco, allow_nil: true,  inclusion: { in: %w( conjugue filho),
  message: "%{value} não é uma parentesco validos, as parentesco validss são: ['conjugue', 'filho'] "}
  validates :matricula, presence: true, if: :titular?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  belongs_to :organizacao
  belongs_to :titular, class_name: 'Beneficiario', foreign_key: :titular_id, optional: true
  has_many :dependentes, class_name: 'Beneficiario', foreign_key: :titular_id, dependent: :destroy
  has_one :beneficio, dependent: :destroy
  has_one :condicao, through: :beneficio
  has_one :organizacao_plano, through: :beneficio
  has_one :plano, through: :organizacao_plano
  has_one :conta_bancaria, dependent: :destroy
  has_one :endereco, dependent: :destroy

  def carteirinha
    beneficio ? beneficio.carteirinha : nil
  end

  def nome_titular
    titular ? titular.name : nil
  end
  def titular?
    self.titular.nil?
  end

  def perfil
    self.titular? ? 'tiular' : 'dependente'
  end

  protected

  def password_required?
    confirmed? ? super : false
  end

  def self.authenticate(email, password)
    beneficiario = Beneficiario.find_for_authentication(email: email)
    beneficiario&.valid_password?(password) ? beneficiario : nil
  end

  private

  def titular_nao_pode_ter_titular
    if self.titular && self.titular.titular
      errors.add(:titular, "Um titular não pode apontar a outro titular")
    end
  end
end

app/controllers/api/v1/beneficiarios_controller.rb
class Api::V1::BeneficiariosController < Api::V1::BaseController
  before_action :set_beneficiario, only: [:show,:update]
  before_action :set_organizacao, only: [:create, :update, :index]
  skip_after_action :verify_policy_scoped

  def index
    authorize @organizacao
    @beneficiarios = Beneficiario.where(organizacao: @organizacao)
  end

  def show
    authorize @beneficiario
  end

  def create
    @beneficiario = @organizacao.beneficiarios.build(beneficiario_params)
    authorize @beneficiario
    if @beneficiario.save
      render :show, status: :created
    else
      render_error(@beneficiario)
    end
  end

  def update
    authorize @beneficiario
    if @beneficiario.update(beneficiario_params)
      render :show, status: :created
    else
      render_error(@beneficiario)
    end
  end

  private

  def set_beneficiario
    @beneficiario = Beneficiario.find(params[:id])
  end

  def set_organizacao
    @organizacao = Organizacao.find(params[:organizacao_id])
  end

  def beneficiario_params
    params.require(:beneficiario).permit(*Beneficiario.params)
  end

end

app/controllers/beneficiarios/confirmations_controller.rb
# frozen_string_literal: true

class Beneficiarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end

  protected
  def after_confirmation_path_for(resource_name, resource)
    token = resource.send(:set_reset_password_token)
    edit_beneficiario_password_path(resource, reset_password_token: token)
  end
end

app/controllers/beneficiarios/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Beneficiarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/beneficiarios/passwords_controller.rb
# frozen_string_literal: true

class Beneficiarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/beneficiarios/registrations_controller.rb
# frozen_string_literal: true

class Beneficiarios::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  include Accessible
  skip_before_action :check_user, except: [:new, :create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/beneficiarios/sessions_controller.rb
# frozen_string_literal: true

class Beneficiarios::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, only: :destroy

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/beneficiarios/unlocks_controller.rb
# frozen_string_literal: true

class Beneficiarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/beneficiarios_controller.rb
class BeneficiariosController < ApplicationController
  before_action :get_organizacao
  before_action :set_beneficiario, only: [:show, :edit, :update, :destroy]
  # include Accessible
  # skip_before_action :check_user, only: [:destroy,:show]

  def index
    @beneficiarios = policy_scope(@organizacao.beneficiarios)
  end

  def show
    # skip_authorization
    authorize @beneficiario
  end

  def new
    @beneficiario = @organizacao.beneficiarios.build
    authorize @beneficiario
  end

  def edit
    authorize @beneficiario
  end

  def create
    @beneficiario = @organizacao.beneficiarios.build(beneficiario_params)
    authorize @beneficiario

    respond_to do |format|
      if @beneficiario.save
        format.html { redirect_to  organizacao_beneficiario_path(@beneficiario.organizacao, @beneficiario), notice: 'beneficiario was successfully created.' }
        format.json { render :show, status: :created, location: @beneficiario }
      else
        format.html { render :new }
        format.json { render json: @beneficiario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      authorize @beneficiario
      if @beneficiario.update(beneficiario_params)
        format.html { redirect_to beneficiario_show, notice: 'Beneficiario was successfully updated.' }
        format.json { render :show, status: :ok, location: @beneficiario }
      else
        format.html { render :edit }
        format.json { render json: @beneficiario.errors, status: :unprocessable_entity }
      end
    end
  end

  private  
  
  def set_beneficiario
    @beneficiario = @organizacao.beneficiarios.find(params[:id])
    
  end

  def beneficiario_params
    attributes = [:id,
    :email,
    :encrypted_password,
    :password,
    :reset_password_token,
    :reset_password_sent_at,
    :remember_created_at,
    :sign_in_count,
    :current_sign_in_at,
    :last_sign_in_at,
    :current_sign_in_ip,
    :last_sign_in_ip,
    :nome,
    :nacionalidade,
    :cpf,
    :sexo,
    :data_nascimento,
    :estado_civil,
    :nome_da_mae,
    :telefone,
    :cargo,
    :admissao,
    :salario,
    :papel,
    :organizacao_id,
    :created_at,
    :genero,
    :sobre_nome,
    :updated_at,
    :titular_id]
    params.require(:beneficiario).permit(*attributes)
  end

  def get_organizacao
    @organizacao = Organizacao.find(params[:organizacao_id])
  end

  def beneficiario_show
    organizacao_beneficiario_path(@beneficiario.organizacao, @beneficiario)
  end
end

app/views/beneficiarios/_beneficiario_info_card.html.erb
<div class="card beneficiario-info-card">
  <div class="model-card">
    <div class="card-body">
      <h5 class='card-title'><%= beneficiario.name %></h5>
      <div class="card-text">
        <p>
          <strong>Email:</strong>
          <%= beneficiario.email %>
        </p>
        <p>
          <strong>Telefone:</strong>
          <%= beneficiario.telefone %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/beneficiarios/_form.html.erb
<%= simple_form_for([@organizacao, @beneficiario], html:{class: 'form-model'} )do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-group">
    <h3>Beneficiario</h3>
    <div class="row">
      <div class="col-12 col-sm-6">
        <%= f.input :nome %>
      </div>
      <div class="col-12 col-sm-6">
        <%= f.input :sobre_nome %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-sm-3">
        <%= f.input :cpf %>
      </div>
      <div class="col-12 col-sm-3">
        <%= f.input :nacionalidade %>
      </div>
      <div class="col-12 col-sm-3">
        <%= f.input :genero, collection: ['homem','mulher']%>
      </div>
      <div class="col-12 col-sm-3">
        <%= f.input :data_nascimento %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-sm-4">
        <%= f.input :email %>
      </div>
       <div class="col-12 col-sm-4">
        <%= f.input :password %>
      </div>
    </div>

  </div>
  <%= f.button :submit , value: 'Salvar', class:'btn btn-primary' %>

<% end%>

app/views/beneficiarios/edit.html.erb
<div class='form-model-container  container-fluid'>
  <h1>Editar Beneficiario</h1>
  <%= render 'form', beneficiario: @beneficiario, url: organizacao_beneficiario_path(@beneficiario.organizacao) %>
  <%= link_to back_button, organizacao_path(@beneficiario.organizacao) %>
</div>

app/views/beneficiarios/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1>Beneficiarios</h1>

  <div class="container  m-3 p-3">
    <%= link_to 'Adicionar Beneficiario', new_organizacao_beneficiario_path,  class: 'btn btn-light-blue' %>
  </div>
    <table class='ui celled table'>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Sobrenome</th>
          <th>Genero</th>
          <th>cpf</th>
          <th>email</th>
          <th>Organizacao</th>
          <th colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @beneficiarios.each do |beneficiario| %>
          <tr>
            <td><%= link_to beneficiario.nome, organizacao_beneficiario_path(beneficiario.organizacao, beneficiario)	 %></td>
            <td><%= beneficiario.sobre_nome %></td>
            <td><%= beneficiario.genero.capitalize %></td>
            <td><%= beneficiario.cpf %></td>
            <td><%= beneficiario.email %></td>
            <td><%= beneficiario.organizacao.nome_fantasia %></td>
            <td><%= link_to edit_button , edit_organizacao_beneficiario_path(beneficiario.organizacao,beneficiario) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>

app/views/beneficiarios/new.html.erb
<div class='form-model-container  container-fluid'>
  <h1>Novo Beneficiario</h1>
  <%= render 'form', beneficiario: @beneficiario, url: nil %>
  <%= link_to back_button, organizacao_path(@beneficiario.organizacao) %>
</div>

app/views/beneficiarios/show.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>
  <h1> Aqui Beneficiario show </h1>
  <%= render 'beneficiario_info_card', beneficiario: @beneficiario %>
</div>