config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: 'custom_tokens'
    skip_controllers :authorizations, :applications, :authorized_applications

  end

  resources :conta_bancarias
  resources :seguradoras
  resources :planos

  resources :beneficios

  devise_for :users, path: 'u', controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  devise_for :beneficiarios, path: 'b', controllers: {
    sessions: "beneficiarios/sessions",
    passwords: "beneficiarios/passwords",
    registrations: "beneficiarios/registrations",
    confirmations: "beneficiarios/confirmations",
    unlocks: "beneficiarios/unlocks"
  }


  resources :organizacoes do
    resources :users, controller: 'organizacao_users', path: 'users'
    resources :organizacao_plano, controller: 'organizacao_planos', path: 'planos'
    resources :beneficiarios
  end


  namespace :api, defaults: {format: :json} do
    post 'password_reset' , to: 'passwords#reset'
    post 'confirm_user', to: 'confirmations#confirm'
    namespace :v1 do
      get 'me', to: 'me#me'
      resources :organizacoes do
        get 'beneficiarios/tickets', to: 'tickets#beneficiarios'
        resources :beneficiarios
        resources :organizacao_planos, path: 'planos'
        resources :condicoes
        resources :beneficios
        resources :users, controller: 'organizacao_users', only: [:index,:create]

      end
      resources :seguradoras do
        resources :planos
      end
      resources :users
      resources :organizacao_planos, only: [:create,:update]
      resources :tickets, except: [:update]
      post 'tickets/:id/cancel', to: 'tickets#cancel'
      post 'tickets/:id/execute', to: 'tickets#execute'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/seguradora.rb
class Seguradora < BaseModel
  has_many :planos, dependent: :destroy
  validates :cnpj, presence: true, cnpj: true

end

app/controllers/api/v1/seguradoras_controller.rb
class Api::V1::SeguradorasController < Api::V1::BaseController
  before_action :set_seguradora, only:[:show, :update]

  def index
    authorize Seguradora
    @seguradoras = policy_scope(Seguradora)
  end

  def show
    authorize @seguradora
  end

  def create
    @seguradora = Seguradora.new(seguradora_params)
    authorize @seguradora
    if @seguradora.save
      render :show, status: :created
    else
      render_error(@seguradora)
    end
  end

  def update
    authorize @seguradora
    if @seguradora.update(seguradora_params)
      render :show
    else
      render_error(@seguradora)
    end
  end

  private

  def set_seguradora
    @seguradora = Seguradora.find(params[:id])
  end

  def seguradora_params
    params.require(:seguradora).permit(*Seguradora.params)
  end
 
end

app/controllers/seguradoras_controller.rb
class SeguradorasController < ApplicationController
  before_action :set_seguradora, only: [:show, :edit, :update, :destroy]

  # GET /seguradoras
  # GET /seguradoras.json
  def index
    @seguradoras = Seguradora.all
  end

  # GET /seguradoras/1
  # GET /seguradoras/1.json
  def show
  end

  # GET /seguradoras/new
  def new
    @seguradora = Seguradora.new
  end

  # GET /seguradoras/1/edit
  def edit
  end

  # POST /seguradoras
  # POST /seguradoras.json
  def create
    @seguradora = Seguradora.new(seguradora_params)

    respond_to do |format|
      if @seguradora.save
        format.html { redirect_to @seguradora, notice: 'Seguradora was successfully created.' }
        format.json { render :show, status: :created, location: @seguradora }
      else
        format.html { render :new }
        format.json { render json: @seguradora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seguradoras/1
  # PATCH/PUT /seguradoras/1.json
  def update
    respond_to do |format|
      if @seguradora.update(seguradora_params)
        format.html { redirect_to @seguradora, notice: 'Seguradora was successfully updated.' }
        format.json { render :show, status: :ok, location: @seguradora }
      else
        format.html { render :edit }
        format.json { render json: @seguradora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seguradoras/1
  # DELETE /seguradoras/1.json
  def destroy
    @seguradora.destroy
    respond_to do |format|
      format.html { redirect_to seguradoras_url, notice: 'Seguradora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seguradora
      @seguradora = Seguradora.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seguradora_params
      params.require(:seguradora).permit(:cnpj, :razao_social, :nome)
    end
end

app/views/seguradoras/_form.html.erb
<%= simple_form_for(@seguradora) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :cnpj %>
    <%= f.input :razao_social %>
    <%= f.input :nome %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/seguradoras/edit.html.erb
<h1>Editing Seguradora</h1>

<%= render 'form', seguradora: @seguradora %>

<%= link_to 'Show', @seguradora %> |
<%= link_to 'Back', seguradoras_path %>

app/views/seguradoras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seguradoras</h1>

<table>
  <thead>
    <tr>
      <th>Cnpj</th>
      <th>Razao social</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seguradoras.each do |seguradora| %>
      <tr>
        <td><%= seguradora.cnpj %></td>
        <td><%= seguradora.razao_social %></td>
        <td><%= seguradora.nome %></td>
        <td><%= link_to 'Show', seguradora %></td>
        <td><%= link_to 'Edit', edit_seguradora_path(seguradora) %></td>
        <td><%= link_to 'Destroy', seguradora, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seguradora', new_seguradora_path %>

app/views/seguradoras/new.html.erb
<h1>New Seguradora</h1>

<%= render 'form', seguradora: @seguradora %>

<%= link_to 'Back', seguradoras_path %>

app/views/seguradoras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @seguradora.cnpj %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @seguradora.razao_social %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @seguradora.nome %>
</p>

<%= link_to 'Edit', edit_seguradora_path(@seguradora) %> |
<%= link_to 'Back', seguradoras_path %>