config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: 'custom_tokens'
    skip_controllers :authorizations, :applications, :authorized_applications

  end

  resources :conta_bancarias
  resources :seguradoras
  resources :planos

  resources :beneficios

  devise_for :users, path: 'u', controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  devise_for :beneficiarios, path: 'b', controllers: {
    sessions: "beneficiarios/sessions",
    passwords: "beneficiarios/passwords",
    registrations: "beneficiarios/registrations",
    confirmations: "beneficiarios/confirmations",
    unlocks: "beneficiarios/unlocks"
  }


  resources :organizacoes do
    resources :users, controller: 'organizacao_users', path: 'users'
    resources :organizacao_plano, controller: 'organizacao_planos', path: 'planos'
    resources :beneficiarios
  end


  namespace :api, defaults: {format: :json} do
    post 'password_reset' , to: 'passwords#reset'
    post 'confirm_user', to: 'confirmations#confirm'
    namespace :v1 do
      get 'me', to: 'me#me'
      resources :organizacoes do
        get 'beneficiarios/tickets', to: 'tickets#beneficiarios'
        resources :beneficiarios
        resources :organizacao_planos, path: 'planos'
        resources :condicoes
        resources :beneficios
        resources :users, controller: 'organizacao_users', only: [:index,:create]

      end
      resources :seguradoras do
        resources :planos
      end
      resources :users
      resources :organizacao_planos, only: [:create,:update]
      resources :tickets, except: [:update]
      post 'tickets/:id/cancel', to: 'tickets#cancel'
      post 'tickets/:id/execute', to: 'tickets#execute'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/organizacoes_controller.rb
class Api::V1::OrganizacoesController < Api::V1::BaseController
  before_action :set_organizacao, only:[:show, :update]

  def index
    authorize Organizacao
    @organizacoes = policy_scope(Organizacao)
  end

  def show
    authorize @organizacao
  end

  def create
    @organizacao = Organizacao.new(organizacao_params)
    authorize @organizacao
    if @organizacao.save
      render :show, status: :created
    else
      render_error(@organizacao)
    end
  end

  def update
    authorize @organizacao
    if @organizacao.update(organizacao_params)
      render :show
    else
      render_error(@organizacao)
    end
  end

  private

  def set_organizacao
    @organizacao = Organizacao.find(params[:id])
  end

  def organizacao_params
    params.require(:organizacao).permit(*Organizacao.params, endereco_attributes: [*Endereco.params, :_destroy])
  end

end

app/controllers/organizacoes_controller.rb
class OrganizacoesController < ApplicationController
  before_action :set_organizacao, only: [:show, :edit, :update, :destroy]

  # GET /organizacoes
  # GET /organizacoes.json
  def index
    @organizacoes = policy_scope(Organizacao)
  end

  # GET /organizacoes/1
  # GET /organizacoes/1.json
  def show
    @organizacao = Organizacao.find(params[:id])
    authorize @organizacao
  end

  # GET /organizacoes/new
  def new
    @organizacao = Organizacao.new
    @organizacao.endereco = Endereco.new
    @organizacao.users.build

    authorize @organizacao

  end

  # GET /organizacoes/1/edit
  def edit
    authorize @organizacao
  end

  # POST /organizacoes
  # POST /organizacoes.json
  def create
    @organizacao = Organizacao.new(organizacao_params)
    authorize @organizacao

    respond_to do |format|
      if @organizacao.save
        format.html { redirect_to @organizacao, notice: 'Organizacao was successfully created.' }
        format.json { render :show, status: :created, location: @organizacao }
      else
        format.html { render :new }
        format.json { render json: @organizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizacoes/1
  # PATCH/PUT /organizacoes/1.json
  def update
    respond_to do |format|
      authorize @organizacao
      if @organizacao.update(organizacao_params)
        format.html { redirect_to @organizacao, notice: 'Organizacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @organizacao }
      else
        format.html { render :edit }
        format.json { render json: @organizacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizacoes/1
  # DELETE /organizacoes/1.json
  def destroy
    authorize @organizacao
    # Not implemented for safety
    
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organizacao
    @organizacao = Organizacao.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def organizacao_params
    params.require(:organizacao).permit(:slug, :razao_social, :cnpj,:nome_fantasia, :inscricao_municipal, :inscricao_estadual,
      endereco_attributes: [:id, :logradouro, :numero, :complemento, :bairro, :cidade, :estado, :cep, :organizacao_id, :beneficiario_id, :created_at, :updated_at, :_destroy],
      users_attributes: [:id, :email, :organizacao_id, :phone, :first_name, :last_name,:password, :_destroy]
    )
  end
end

app/views/organizacoes/_form.html.erb
<%= simple_form_for(@organizacao, html:{class:'form-model '}) do |f| %>
  

    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
  <div class="form-group">
    <%= f.simple_fields_for :users do |user_form|  %>
      <%= render 'users_fields' , f: user_form %>
      
    <% end%>
    <div class="links">
        <%= link_to_add_association 'Adicionar responsável', f,  :users, partial: 'users_fields', class: 'btn btn-info' %>
      </div>


  </div>
  <div class="form-group">
    <h3>Dados cadastrais</h3>
    <div class="form-inputs">
      <%= f.input :slug %>
      <%= f.input :nome_fantasia %>
      <%= f.input :razao_social %>
      <%= f.input :cnpj %>
      <%= f.input :inscricao_municipal %>
      <%= f.input :inscricao_estadual %>
    </div>
  </div>
  <div class="form-group">
    <h3>Endereço</h3>
    <%= f.simple_fields_for :endereco do |endereco_form| %>
      <div class="row">
        <div class="col-sm-6 col-12">
          <%= endereco_form.input :logradouro %>
        </div>
        <div class="col-sm-2 col-12">
          <%= endereco_form.input :numero %>
        </div>
        <div class="col-sm-4 col-12">
          <%= endereco_form.input :bairro %>
        </div>
        <div class="col-sm-4 col-12">
          <%= endereco_form.input :cidade %>
        </div>
        <div class="col-sm-4 col-12">
          <%= endereco_form.input :estado %>
        </div>
        <div class="col-sm-4 col-12">
          <%= endereco_form.input :cep %>
        </div>
      </div>
    <%end %>
  

  <div class="form-actions">
    <%= f.button :submit , value: 'Salvar', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/organizacoes/_organizacao_info_card.html.erb
<div class="card organizacao-info-card">
  <div class="model-card">
    <div class="card-body">
    <h5 class='card-title'>
        <%= @organizacao.nome_fantasia %>
      </h5>
      <div class="card-text">  
        <p>
          <strong>Razao social:</strong>
          <%= @organizacao.razao_social %>
        </p>
        <p>
          <strong>Cnpj:</strong>
          <%= @organizacao.cnpj %>
        </p>
        <p>
          <strong>Inscrição Municipal:</strong>
          <%= @organizacao.inscricao_municipal %>
        </p>
        <p>
          <strong>Inscrição Estadual:</strong>
          <%= @organizacao.inscricao_estadual %>
        </p>
        <%= link_to edit_button, edit_organizacao_path(@organizacao) %>
      </div>
    </div>

  </div>
</div>

app/views/organizacoes/_organizacao_users_info_card.html.erb
<div class="card organizacao-user-info-card">
  <div class="model-card">
    <div class="card-body">
      <h5 class='card-title'><%= user.name %></h5>
      <div class="card-text">
        <p>
          <strong>Email:</strong>
          <%= user.email %>
        </p>
        <p>
          <strong>Telefone:</strong>
          <%= user.phone %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/organizacoes/_plano_card.html.erb
<div class="card organizacao-info-card">
  <div class="model-card">
    <div class="card-body">
      <h5>
          Nome do plano: <%= plano.nome %>
      </h5>
      <h5>
        Seguradora: <%= plano.seguradora.nome%>
      </h5>
      <div class="card-text">  
        <p>
          <strong>Premio mensal:</strong>
          <%= plano.premio_mensal%>
        </p>
        <p>
          <strong>Papel</strong>
          <%= plano.papel %>
        </p>
        <p>
          <strong>Acomodaçaõ</strong>
          <%= plano.acomodacao %>
        </p>
      </div>
      <% org_plano =  OrganizacaoPlano.find_by(plano: plano, organizacao: @organizacao) %>
      <%= link_to delete_button, organizacao_organizacao_plano_path(org_plano.organizacao, org_plano), method: "delete", data:{confirm: "Têm certeza?"} %>
    </div>

  </div>
</div>

app/views/organizacoes/_users_fields.html.erb
<div class="fields-organizacao-users nested-fields">
  <h3>Responsável</h3>
  <div class="row">
    <div class="col-sm-6 col-12">
      <%= f.input :first_name %>
    </div>
      <div class="col-sm-6 col-12">
      <%= f.input :last_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-12">
      <%= f.input :email %>
    </div>
      <div class="col-sm-6 col-12">
      <%= f.input :phone %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-12">
       <%= f.input :password %>
    </div>
  </div>
  <%= link_to_remove_association 'Remover responsável', f, class:'btn btn-warning' %>
</div>

app/views/organizacoes/edit.html.erb
<div class='form-model-container  container-fluid'>
  <h1>Editar Organização</h1>
  <%= render 'form', organizacao: @organizacao %>
  <%= link_to back_button, organizacoes_path %>
</div>

app/views/organizacoes/index.html.erb
<p id="notice"><%= notice %></p>
  <h1>Organizacoes</h1>
  <%= link_to 'Criar nova organização', new_organizacao_path ,class: 'btn btn-light-blue' if internal_user? %>


  <table class='ui celled table'>
    <thead>
      <tr>
        <th>Razao social</th>
        <th>Nome de fantasia</th>
        <th>Cnpj</th>
        <th>Inscrição Estadual</th>
        <th>Inscrição Municipal</th>
        <th>Usuarios</th>
        <th>Beneficiarios</th>
        <th>Slug</th>
        <th colspan="3">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @organizacoes.each do |organizacao| %>
        <tr>
          <td><%= link_to organizacao.razao_social, organizacao %></td>
          <td><%= organizacao.nome_fantasia %></td>
          <td><%= organizacao.cnpj %></td>
          <td><%= organizacao.inscricao_municipal %></td>
          <td><%= organizacao.inscricao_estadual %></td>
          <td><%= organizacao.users.size %></td>
          <td><%= organizacao.beneficiarios.size %></td>
          <td><%= organizacao.slug %></td>
          <% edit_button= '<div class="ui icon button blue" data-tooltip="Editar"><i class="edit outline icon"></i></div>'.html_safe%>
          <td><%= link_to edit_button, edit_organizacao_path(organizacao) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

app/views/organizacoes/new.html.erb
<div class="form-model-container  container-fluid">

  <h1>Nova Organização</h1>

  <%= render 'form', organizacao: @organizacao %>

  <%= link_to back_button, organizacoes_path %>


</div>

app/views/organizacoes/show.html.erb
<div class="container-fluid organizacao-container padding-margin"> 
  <p id="notice"><%= notice %></p>
  <h2>Informação da empresa</h2>
  <div class="row">
    <%= render 'organizacao_info_card'%>
  </div>
  <h2>Responsaveis</h2>
  <div class="row">
    <% @organizacao.users.each do |user|%>
      <div class="col-12 col-sm-4">
        <%= render 'organizacao_users_info_card', user: user %>
      </div>
    <% end%>
  </div>
  <div class="row">
    <h2>Beneficiarios</h2>
    <div class="container m-3 p-3 ">
      <%= link_to " Ver beneficarios", organizacao_beneficiarios_path(@organizacao), class: 'btn-lg btn-primary' %>
    </div>
  </div>


  <% if current_user.internal? %>
    <div class="row">
      <h2>Planos activos para empresa: <%= @organizacao.nome_fantasia %></h2>
      <div class="container m-3 p-3 ">
        <div class="row">
          <% @organizacao.planos.each do |plano| %>
            <%= render 'plano_card', plano: plano %>
          <% end %>
        </div>
        <%= link_to " Adicionar plano ", new_organizacao_organizacao_plano_path(@organizacao), class: 'btn-lg btn-primary' %>
      </div>
    </div>
  <% end %>

  <%= link_to back_button, organizacoes_path %>
</div>