config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: 'custom_tokens'
    skip_controllers :authorizations, :applications, :authorized_applications

  end

  resources :conta_bancarias
  resources :seguradoras
  resources :planos

  resources :beneficios

  devise_for :users, path: 'u', controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  devise_for :beneficiarios, path: 'b', controllers: {
    sessions: "beneficiarios/sessions",
    passwords: "beneficiarios/passwords",
    registrations: "beneficiarios/registrations",
    confirmations: "beneficiarios/confirmations",
    unlocks: "beneficiarios/unlocks"
  }


  resources :organizacoes do
    resources :users, controller: 'organizacao_users', path: 'users'
    resources :organizacao_plano, controller: 'organizacao_planos', path: 'planos'
    resources :beneficiarios
  end


  namespace :api, defaults: {format: :json} do
    post 'password_reset' , to: 'passwords#reset'
    post 'confirm_user', to: 'confirmations#confirm'
    namespace :v1 do
      get 'me', to: 'me#me'
      resources :organizacoes do
        get 'beneficiarios/tickets', to: 'tickets#beneficiarios'
        resources :beneficiarios
        resources :organizacao_planos, path: 'planos'
        resources :condicoes
        resources :beneficios
        resources :users, controller: 'organizacao_users', only: [:index,:create]

      end
      resources :seguradoras do
        resources :planos
      end
      resources :users
      resources :organizacao_planos, only: [:create,:update]
      resources :tickets, except: [:update]
      post 'tickets/:id/cancel', to: 'tickets#cancel'
      post 'tickets/:id/execute', to: 'tickets#execute'
    end
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/menus/_beneficiario_sidebar_content.html.erb
<a class="item" href=<%= organizacao_beneficiario_path(current_beneficiario.organizacao, current_beneficiario)%>>
  <i class="home icon"></i>
  Beneficiario 1
</a>

app/views/shared/menus/_client_sidebar_content.html.erb
<a class="item" href="<%= organizacao_path(current_user.organizacao)%>">
  <i class="building icon"></i>
  Minha empresa
</a>

app/views/shared/menus/_internal_sidebar_content.html.erb
<a class="item" href=<%= organizacoes_path%>>
  <i class="building outline icon"></i>
  Organizações
</a>

app/views/shared/menus/_sidebar.html.erb
<!-- TODO -->
<% if user_logged_in? %>
  <div class=" ui vertical menu  inverted labeled icon menu ">
      <%= render "shared/menus/#{current_user_or_beneficiario.sidebar_content}" %>
  </div>
<% end %>